spring:
  application:
    name: project-center-demo
  profiles:
    active: local
  dubbo:
    application:
      name: project-center-demo
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    registry:
      check: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
swagger:
  base-package: com.lytongxue.controller
  info:
    title: project-center-demo
server:
  port: 8080
  servlet:
    context-path: /project-center-demo
logging:
  file: 'logs/${spring.application.name}.log'
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
